--CREATING CUSTOMERS TABLE
CREATE TABLE
     CUSTOMERS (
     CUSTOMER_ID INT PRIMARY KEY, 
	 CUSTOMER_NAME VARCHAR(255) NOT NULL, 
     CUSTOMER_TEL VARCHAR(13) NOT NULL);

--CREATING PRODUCTS TABLE
CREATE TABLE
     PRODUCTS (
	 PRODUCT_ID INT PRIMARY KEY, 
	 PRODUCT_NAME VARCHAR(255) NOT NULL, 
	 CATEGORY VARCHAR(255) NOT NULL,
	 PRICE DECIMAL NOT NULL CHECK(PRICE> 0));

--CREATING ORDERS TABLE
CREATE TABLE
     ORDERS (
	 ORDER_ID INT PRIMARY KEY,
	 CUSTOMER_ID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMERS(CUSTOMER_ID), 
	 PRODUCT_ID INT NOT NULL FOREIGN KEY REFERENCES PRODUCTS(PRODUCT_ID),
	 QUANTITY INT NOT NULL,
	 ORDER_DATE DATE NOT NULL);

--TO ALTER ORDERS TABLE AND ADD TOTAL AMOUNT
ALTER TABLE 
    ORDERS ADD TOTAL_AMOUNT DECIMAL NOT NULL;